#CLAUSE LESSON 10-25
USE employees;
SELECT * 
FROM employees
WHERE hire_date >= '1990-01-01';

# TO FIND THOSE HIRED IN THE 1990'S

select *
from employees
where hire_date LIKE '1990%';

# TO FIND THOSE HIRED IN MONTH OFOCTOBER
SELECT *
FROM employees
WHERE hire_date LIKE '%-10-%';

# TO FIND THOSE NOT HIRED IN MONTH OF OCTOBER 	
SELECT *
FROM employees
WHERE hire_date NOT LIKE '%-10-%';

#TO FIND THOSE HIRED BETWEEN 1990 AND 1999
SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31';

#TO FIND THOSE WHOSE FIRST NAMES START WITH S
SELECT *
FROM employees
WHERE first_name LIKE 'S%';

#TO FIND THOSE WHOSE FIRST NAMES START WITH S AND ENDS WITH S
SELECT *
FROM employees
WHERE first_name LIKE 'S%s';

#TO FIND THOSE FIRST NAMES AND LAST NAMES START WITH S
SELECT *
FROM employees
WHERE first_name LIKE 'S%' AND last_name LIKE 'S%';

#TO FIND THOSE FIRST NAMES START WITH S OR LAST NAME STARTS WITH S
SELECT *
FROM employees
WHERE first_name LIKE 'S%' OR last_name LIKE 'S%';

#TO FIND ALL THOSE WHOSE LAST NAME IS EITHER FOOTE OR SIDOU
SELECT *
FROM employees
WHERE last_name = 'Foote' OR last_name = 'Sidou';

SELECT *
FROM employees
WHERE last_name IN ('Foote', 'Sidou');

#ANY RECORDS WHERE HIRE DATE IS NULL?
SELECT *
FROM employees
WHERE hire_date IS NULL;

#ANY RECORDS WHERE HIRE DATE IS NOT NULL?
SELECT *
FROM employees
WHERE hire_date IS NOT NULL;

#FIND EMPLOYEES WHO WERE HIRED IN THE 90S AND FIRST NAME STARTS WITH S OR LAST NAME STARTS WITH S

SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31'
AND (first_name LIKE 'S%' OR last_name LIKE 'S%');


#EMPLOYEES HIRED IN THE 90, ORDER BY HIRE DATE ASCENDING
SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31'
ORDER BY hire_date ASC;

#EMPLOYEES HIRED IN THE 90, ORDER BY HIRE DATE DESCENDING
SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31'
ORDER BY hire_date DESC;

#EMPLOYEES 
SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31'
ORDER BY hire_date ASC, gender DESC;

DESCRIBE employees;

#ALL MALES FIRST BY HIRE DATE AND THEN ALL THE FEMALES BY HIRE DATE
SELECT *
FROM employees
WHERE hire_date BETWEEN '1990-01-01' AND '1999-12-31'
ORDER BY gender ASC, hire_date DESC;

# ADDING LIMITS TO OUTPUT
# FIND OLDEST EMPLOYEE HIRED IN 1990
SELECT *
FROM employees
WHERE hire_date LIKE '1990%'
ORDER BY birth_date ASC
LIMIT 5;

SELECT *
FROM employees
WHERE hire_date LIKE '1990%'
ORDER BY birth_date ASC, first_name ASC
LIMIT 5 OFFSET 3;



 	